homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

def profile(request):
    return render(request, 'profile.html')

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Story 1</title>
<link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
  <nav class="navbar navbar-expand-sm navbar-dark"> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto"> 
          <li class="nav-item"> 
            <a id = "a" class="nav-link" href="{% url 'homepage:index' %}">Home</a>
          </li> 
          <li class="nav-item"> 
            <a id = "a" class="nav-link" href="{% url 'homepage:profile' %}">Profile</a>
          </li> 
      </ul> 
    </div>
</nav>

  <div class="container">
    <div class="row">
        <div class="col-md-6 align-self-center">
          <img class = "profileimg" src="{% static 'foto-profil.JPG' %}">
        </div>
        <div class="col-md-6" style="margin-top:5%">
          <h1 class="h"><mark id="mark">Syifa Rizka Sagita</mark></h1>
          <h2 class="h"><mark id="mark">1906299181</mark></h2>
          <div>
            <p>Mahasiswi Sistem Informasi Universitas Indonesia angkatan 2019 yang memiliki ketertarikan pada dunia IT dan senang mencoba hal-hal baru. Di waktu senggang saya hobi menonton film serta acara tv</p>
            <p>Riwayat Pendidikan:</p>
            <ul>
              <li>Universitas Indonesia (2019 - Sekarang)</li>
              <li>SMAN 68 Jakarta (2016 - 2019)</li>
              <li>SMPN 216 Jakarta (2013 - 2016)</li>
            </ul> 
          </div>
          <a id = "a" class="btn" href="{% url 'homepage:profile' %}" role="button">About Me</a>
          <a id = "a" class="round-btn btn" href="https://www.instagram.com/syifarizka/" target="_blank"><i id = "iconsfa" class="fab fa-instagram"></i></a>
          <a id = "a" class="round-btn btn" href="https://www.linkedin.com/in/syifa-rizka-sagita/" target="_blank"><i id = "iconsfa" class="fab fa-linkedin-in"></i></a>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>


</body>
</html>

homepage/templates/profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Story 3</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-sm navbar-dark" style="background-color:#89ABE3FF;"> 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto"> 
      <li class="nav-item"> 
        <a id = "a" class="nav-link" href="{% url 'homepage:index' %}">Home</a>
      </li> 
      <li class="nav-item"> 
        <a id = "a" class="nav-link" href="{% url 'homepage:profile' %}">Profile</a>
      </li> 
    </ul> 
  </div>
</nav>

<div class="container">
  <div class="row">
    <div class="col-md-12 align-self-center">
      <h1 class="h"><mark id="mark">My Profile</mark></h1>
    </div>
    <div class="col-sm-6" style="margin-top:7%">
      <h3 class="h">Riwayat Pendidikan</h3>
        <ul style="padding-left: 50px;">
          <li>Universitas Indonesia (2019 - Sekarang)</li>
          <li>SMAN 68 Jakarta (2016 - 2019)</li>
          <li>SMPN 216 Jakarta (2013 - 2016)</li>
        </ul> 
    </div>
    <div class="col-sm-6" style="margin-top:7%">
      <h3 class="h">Riwayat Organisasi dan Kepanitiaan</h3>
        <ul>
          <li>DPM Fasilkom UI 2020</li>
          <li>PMB Fasilkom UI 2020</li>
          <li>PERAK Fasilkom UI 2020</li>
        </ul>  
    </div>
    <div class="col-md-12 align-self-center">
      <h3 class="h">Karya/Project</h3>
        <p class="h">Ditunggu!</p>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>
</html>